### ISSUE TITLE
Práctica de Gestión de Recursos

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-tr#1]
[PRACTICA DE GESTION DE RECURSOS.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-tr/files/7560818/PRACTICA.DE.GESTION.DE.RECURSOS.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 30%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
