### ISSUE TITLE
Práctica Gestión de Riesgos

### ISSUE THREAD

**Issue by EDITH-R** [SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-tr#2]
[Gestión de riesgos-TlaxRoom.pdf](https://github.com/SistemasTecTlaxiaco/practica-planificacion-de-recursos-entrevista-tr/files/7572505/Gestion.de.riesgos-TlaxRoom.pdf)

**Comment by MaGuadalupeQuiroz** [comment]
Calificación: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
